import test from 'node:test';
import assert from 'node:assert/strict';
import { PokerTable, bestHand, handName } from '../server/poker.js';
import { pokerKey, legalActions } from '../public/js/shared/poker-rules.js';
function seat(pid,chips=1000){return {pid,name:'Jugador '+pid,chips,bet:0,total:0,folded:false,allin:false,acted:false,actedAt:0,inHand:true,cards:['2s','3h'],shown:null,timeouts:0,sitOut:false};}
function table(n=3){const t=new PokerTable('qa',n,{broadcast(){},sendTo(){},sys(){}});t._fillBots=()=>{};t.seats=Array.from({length:n},(_,i)=>seat(i+1));t.phase='flop';t.board=['Ah','Kd','7s'];t.deck=['2c','3c','4c','5c','6c','7c','8c','9c'];t.handNo=1;t.dealer=0;t.turn=0;return t;}
test('evaluate five-card combinations correctly with five, six and seven available cards',()=>{assert.equal(handName(bestHand(['As','Ks','Qs','Js','Ts']).score),'Escalera real');assert.equal(bestHand(['Ah','Ad','Kc','Ks','2d','Qh']).score[0],2);assert.equal(bestHand(['Ah','Ad','Kc','Ks','2d','Qh','Ac']).score[0],6);assert.equal(bestHand(['As','2h','3d','4c','5s']).score[1],5);});
test('short all-in does not reopen a completed raise',()=>{const t=table();t.currentBet=100;t.minRaise=100;t.turn=1;for(const s of t.seats){s.bet=100;s.total=100;}t.seats[0].acted=true;t.seats[0].actedAt=100;t.seats[1].chips=50;t.action(2,'allin');t.action(3,'call');assert.equal(t.turn,0);const before=t.seats[0].chips;t.action(1,'raise',250);assert.equal(t.seats[0].chips,before);assert.equal(t.turn,0);t.action(1,'call');assert.equal(t.phase,'turn');});
test('cumulative short all-ins reopen a full raise',()=>{const t=table(4);t.currentBet=100;t.minRaise=100;t.turn=1;for(const s of t.seats){s.bet=100;s.total=100;}t.seats[0].acted=true;t.seats[0].actedAt=100;t.seats[1].chips=50;t.seats[2].chips=100;t.action(2,'allin');t.action(3,'allin');t.action(4,'call');assert.equal(t.turn,0);t.action(1,'raise',350);assert.equal(t.currentBet,350);});
test('no-limit accepts the entire stack beyond the pot size',()=>{const t=table();t.action(1,'raise',1000);assert.equal(t.currentBet,1000);assert.equal(t.seats[0].chips,0);assert.equal(t.seats[0].allin,true);});
test('only each owner receives their own two private cards',()=>{const t=table();const packets=[];t.hooks.sendTo=(id,m)=>packets.push({id,m});t.phase='idle';t._startHand();assert.equal(packets.filter(p=>p.m.t==='pkc').length,3);assert.ok(packets.every(p=>p.m.cards.length===2));for(const s of t.publicState().seats){assert.equal(s.cards,undefined);assert.equal(s.shown,null);}});
test('invalid and undersized raises cannot spend chips',()=>{const t=table();t.currentBet=100;t.minRaise=80;for(const amount of [-50,NaN,Infinity,150]){const before=t.seats[0].chips;t.action(1,'raise',amount);assert.equal(t.seats[0].chips,before);}});
test('side pots refund uncalled excess without declaring the refund a win',()=>{const t=table();t.board=['2c','3d','7h','8s','9c'];t.seats[0].cards=['As','Ah'];t.seats[1].cards=['Ks','Kh'];t.seats[2].cards=['Qs','Qh'];[100,200,400].forEach((n,i)=>Object.assign(t.seats[i],{chips:0,total:n,bet:n,allin:true}));t._showdown();assert.deepEqual(t.seats.map(s=>s.chips),[300,200,200]);assert.ok(!t.result.some(r=>r.seat===2));assert.equal(t.refunds[0].amount,200);});
test('odd chip in a split pot goes clockwise after the dealer',()=>{const t=table();t.board=['As','Ks','Qs','Js','Ts'];t.dealer=0;t.seats.forEach((s,i)=>Object.assign(s,{chips:0,total:5,bet:5,cards:[['2c','3c'],['4c','5c'],['6c','7c']][i]}));t.seats[2].folded=true;t._showdown();assert.deepEqual(t.seats.map(s=>s.chips),[7,8,0]);});
test('all-in blinds run out to showdown rather than deadlocking',()=>{const t=table(2);t.phase='idle';t.seats.forEach(s=>s.chips=5);t._startHand();for(let i=0;i<6&&t.phase!=='showdown';i++)t.tick(Date.now()+5000+i*2000);assert.equal(t.phase,'showdown');});
test('two actual timeouts mark the player absent',()=>{const t=table();t.deadline=1;t.tick(Date.now());assert.equal(t.seats[0].timeouts,1);t.turn=0;t.phase='turn';t.seats[0].acted=false;t.deadline=1;t.tick(Date.now());assert.equal(t.seats[0].sitOut,true);});
test('stale hand/revision cannot perform another action',()=>{const t=table(),before=t.seats[0].chips;assert.equal(t.action(1,'allin',0,{hand:0,revision:0}),false);assert.equal(t.seats[0].chips,before);});
test('leaving with all chips committed retains showdown eligibility',()=>{const t=table();t.seats[0].allin=true;t.seats[0].chips=0;t.seats[0].total=100;t.turn=1;t.leave(1);assert.equal(t.seats[0].folded,false);assert.equal(t.publicState().seats[0].leaving,true);});
test('a player can refill free chips between hands',()=>{const t=table();t.phase='showdown';t.seats[0].chips=0;t.rebuy(1);assert.equal(t.seats[0].chips,2000);});
test('keyboard intents ignore text, modifiers and held action keys',()=>{assert.equal(pokerKey('Space'),'match');assert.equal(pokerKey('KeyF',{repeat:true}),null);assert.equal(pokerKey('KeyT',{typing:true}),null);assert.equal(pokerKey('KeyA',{modified:true}),null);assert.equal(pokerKey('ArrowRight',{repeat:true}),'more');assert.equal(pokerKey('KeyV'),null);});
test('UI distinguishes all-in call from an allowed raise',()=>{const st={phase:'flop',turn:0,currentBet:100,minRaise:100,bb:20,seats:[{chips:30,bet:50,inHand:true,raiseAllowed:false}]};const a=legalActions(st,0);assert.equal(a.pay,30);assert.equal(a.max,80);assert.equal(a.canRaise,false);assert.equal(a.ready,true);});
